### ISSUE TITLE
Getting PersonaChat comet expansion Json

### ISSUE THREAD

**Issue by seyos11** [majumderb/compac#1]
I would like to know if there is a public repository with the new json. I tried to generate (persona_explorations_annotations.py i think is the responsible file) but the process is too long and i don't get the results due to the enormous waste of time it implies. Is there any way to solve this problem, getting this new data faster?? I even tried to avoid every print to get faster but it isn't.

**Comment by majumderb** [comment]
Hello, thank you for your query. We have updated the readme with the json file that also has COMET expansions included. The link is provided here again: https://drive.google.com/file/d/1tJih0IecAmP3IlP6TYvDjy3kOpIbMUIH/view

Please let me know if you have any questions.
