### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by RogerHeederer** [majumderb/compac#2]
Hello, I am interested in your compac model.
So I am trying to download the code and run the model. However, the version often does not match and the experiment does not proceed smoothly.

Could you tell me the version of the various modules in your environment?

requirements.txt
(python, torch, pytorch-ignite, transformers, tensorboardX, etc)

Thank you!

**Comment by majumderb** [comment]
Hello,

Following are the versions of critical modules:

torch 1.4.0
ignite 0.4.0
transformers 2.5.1

You can skip the tensorboardX part altogether in the code. Please let me know if you face any other problems.

**Comment by RogerHeederer** [comment]
Thank you so much for your reply

I am just a beginner in the field of NLP chatbots. Your paper has been read carefully and I am trying to implement it.

Please explain in detail for each folder.

models / baseline_personachat
models / baseline_w_comet
models / discrete_choice_model
models / heuristic_retrieval
models / persona_weak_sup
models / pretraining
models / reinforce_model

Is the final Compac model reinfoce_model?

**Comment by majumderb** [comment]
models / reinforce_model is our best model. Check new updates and fixes.
