### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by PeganovAnton** [majumderb/compac#3]
Hello, I am going to use the COMPAC model in my project.
Could you please provide pretrained COMPAC model? I found only baselines.
Could you please tell me where can I find code and weights for persona expansion?

**Comment by majumderb** [comment]
The persona expansions (no training involved) are available in the readme. 

We don't have pre-trained models but you can train our best model using the following (updated) code:
https://github.com/majumderb/compac/blob/master/models/reinforce_model/train.py
