### ISSUE TITLE
LatentVariableInferenceModel problems

### ISSUE THREAD

**Issue by PeganovAnton** [majumderb/compac#4]
1. The import of `LatentVariableInferenceModel` in file `models/reinforce_model/train.py` is broken. The `LatentVariableInferenceModel` is in `models/reinforce_model/model_with_inferencenw.py` now.
2. `LatentVariableInferenceModel.forward()` returns a tuple of 8 elements whereas in [line](https://github.com/majumderb/compac/blob/c08b7dbc41d5e23caabfa4db64f1d76a7ee87e1b/models/reinforce_model/train.py#L191) I see 6 elements.

**Comment by majumderb** [comment]
This is fixed! Thanks for noting.
