### ISSUE TITLE
prior_posterior_models.py

### ISSUE THREAD

**Issue by wrf222222** [majumderb/compac#8]
Hello, I am going to run the COMPAC. By reading the prior_posterior_models.py, I am a little confused about the calculation of z. 
1. Why use subtraction 'history_encodings - persona_encodings' to calculate the 'norms' in prior?
2. Similar to the last question, (1) 'gt_response = mc_token_ids[:, :, 0]', as we know, 'mc_token_ids' is used to represent the length of 'input_ids' in the code. Does it can be the representation of response? (2) It also use 'gt_response_encodings - persona_encodings' to calculate the 'norms'. Why do we use subtraction here? (3) In the paper, we can see the prior model is a log-linear model, which consists of f1,f2, and f3.  Could you tell me where is the calculation of these features?
Thank you so much!

**Comment by majumderb** [comment]
1. That line of code calculates the L2 norm between `history_encodings` and `persona_encodings`. The intuition is to see which persona is closest to the dialog history
2. `gt_response` is the ground truth response.
3. Similarly, we calculate the L2 norm between `gt_response_encodings` and `persona_encodings` in the posterior model and the closest persona index will have the highest likelihood, as obtained from the softmax in the next line.
4. `f1` is a bilinear product between persona and history encodings, `f2` is a learned preference vector over 9 COMET relations. `f3` is a similar preference vector but now projected along with the history encodings (i.e. history-encodings -> preference vector by a linear projection).
